disabled_rules:
  - trailing_whitespace
  - cyclomatic_complexity
  - private_over_fileprivate
  - todo
  - block_based_kvo
  - redundant_objc_attribute
  - for_where
  - large_tuple
  - function_parameter_count
  - function_body_length
  - type_body_length
  - orphaned_doc_comment

opt_in_rules:
  - empty_count #error
  - private_outlet #warning

file_length:
    warning: 3000
    error: 5000

line_length: 300

type_name:
    min_length:
        warning: 1
    max_length:
        warning: 45
        error: 50
    allowed_symbols: ["_"]

force_cast:
    severity: warning
force_try:
    severity: warning
    
nesting:
    type_level:
        warning: 3
    function_level:
        warning: 5

identifier_name:
    min_length:
        error: 2
    excluded:
        - Log
        - id
        - x
        - y
        - os
        - up
        - i
        - w
        - h
        - Defaults
        - v
        - iv
        - yn
        - URL
    allowed_symbols: ["_"]

excluded:
- Pods
